[package]
name = "datatoaster-core"
publish = false
version.workspace = true

[features]
default = []
std = ["no-std-compat/std"]

[dependencies]
no-std-compat = "0.4"
datatoaster-traits = { path = "../datatoaster-traits" }
